MxOnline/urls.py
# coding: utf-8
"""MxOnline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve

from .settings import MEDIA_ROOT
import xadmin

from users.views import mylogin
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView
from users.views import LogoutView, IndexView
from organization.views import OrgView


urlpatterns = [
    # 富文本插件
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    # 后台管理系统插件
    url(r'^xadmin/', xadmin.site.urls),

    # 静态资源url处理，（xadmin, 支持image字段显示的url配置）
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    # url(r'^static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

    # 处理静态文件
    # url('^$', TemplateView.as_view(template_name="index.html"), name="index"),
    # url('^login/$', TemplateView.as_view(template_name="login.html"), name="login")
    # 基于函数的处理方式
    # url('^login/$', mylogin, name="login")

    # 首页
    url("^$", IndexView.as_view(), name="index"),

    # 登录
    url("^login/$", LoginView.as_view(), name="login"),

    # 退出
    url("^logout/$", LogoutView.as_view(), name="logout"),

    # 注册
    url("^register/$", RegisterView.as_view(), name="register"),

    # 验证码相关url
    url(r'^captcha/', include('captcha.urls')),

    # 激活
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="active"),

    # 忘记密码
    url(r'^forget/$', ForgetPwdView.as_view(), name="forget"),

    # 重置密码链接
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name="reset"),

    # 修改密码
    url(r'^modify/$', ModifyPwdView.as_view(), name="modify"),


    # 课程机构app相关url
    url(r'^org/', include(('organization.urls', 'organization'), namespace="org")),

    # 课程app相关url
    url(r'^course/', include(('courses.urls', 'courses'), namespace="course")),

    # user相关url
    url(r'^users/', include(('users.urls', 'users'), namespace="users")),
]

# 全局404
handler404 = 'users.views.page_not_found'

# 全局 500
handler500 = 'users.views.page_error'

apps/courses/urls.py
# coding: utf-8

from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView

urlpatterns = [
    # 课程列表页
    url(r'^list/$', CourseListView.as_view(), name="course_list"),

    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),

    url(r'^info/(?P<course_id>\d+)/$', CourseInfoView.as_view(), name="course_info"),

    url(r'^comment/(?P<course_id>\d+)/$', CommentsView.as_view(), name="course_comment"),

    url(r'^add_comment/$', AddCommentsView.as_view(), name="add_comment"),

    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name="video_play"),
]

apps/organization/urls.py
# coding: utf-8

from django.conf.urls import url
from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView
from .views import TeacherListView, TeacherDetailView

urlpatterns = [
    # 课程机构列表
    url(r'^list/$', OrgView.as_view(), name="org_list"),
    # 机构首页
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    # 机构课程页
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    # 机构描述页
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    # 机构讲师页
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),

    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    # 添加课程咨询
    url(r'^add_ask/$', AddUserAskView.as_view(), name="add_ask"),

    # 讲师相关，与课程机构公用一个app
    # 讲师列表页
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),
    # 讲师详情页
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),
]

apps/users/urls.py
# coding: utf-8

from django.conf.urls import url
from .views import UserInfoView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView
from .views import MyCourse, MyFavCourse, MyFavOrg, MyFavTeacher, MyMessageView

urlpatterns = [
    # 用户信息
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),

    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name="image_upload"),

    # 用户中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),

    # 用户中心发送邮箱验证码
    url(r'^sendemail_code/$', SendEmailCodeView.as_view(), name="sendemail_code"),

    # 用户中心修改邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    # 用户中心修改邮箱
    url(r'^mycourse/$', MyCourse.as_view(), name="mycourse"),

    # 我的收藏-课程机构
    url(r'^myfav/org/$', MyFavOrg.as_view(), name="myfav_org"),

    # 我的收藏-教师
    url(r'^myfav/teacher/$', MyFavTeacher.as_view(), name="myfav_teacher"),

    # 我的收藏-课程
    url(r'^myfav/course/$', MyFavCourse.as_view(), name="myfav_course"),

    # 我的收藏-课程
    url(r'^mymessage/$', MyMessageView.as_view(), name="mymessage"),

]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/courses/models.py
# coding: utf-8
from __future__ import unicode_literals

from django.db import models
from organization.models import CourseOrg, Teacher
from DjangoUeditor.models import UEditorField


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name="课程机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, verbose_name="课程讲师", null=True, blank=True)
    name = models.CharField(max_length=100, verbose_name="课程名")
    is_banner = models.BooleanField(verbose_name="是否轮播", default=False)
    desc = models.CharField(max_length=300, verbose_name="课程描述")
    detail = UEditorField(verbose_name="课程详情", width=600, height=300, imagePath="courses/ueditor/",
                          filePath="courses/ueditor/", default="")
    degree = models.CharField(choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), verbose_name="难度", max_length=2)
    learn_times = models.IntegerField(verbose_name="学习时长", default=0)
    students = models.IntegerField(verbose_name="学习人数", default=0)
    fav_nums = models.IntegerField(verbose_name="收藏人数", default=0)
    image = models.ImageField(verbose_name="封面", upload_to="courses/%Y/%m")
    click_nums = models.IntegerField(verbose_name="点击数", default=0)
    category = models.CharField(max_length=20, default="后端开发", verbose_name="课程类别")
    tag = models.CharField(default="", max_length=10, verbose_name="课程标签")
    you_need_know = models.CharField(max_length=300, null=True, blank=True, verbose_name="课程须知")
    teacher_tell = models.CharField(max_length=300, null=True, blank=True, verbose_name="老师告诉你")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = "课程"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

    def get_zj_nums(self):
        """获取课程章节数"""
        return self.lesson_set.all().count()
    # 显示在xadmin列表中的名称
    get_zj_nums.short_description = "章节数"

    def go_to(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href='http://www.baidu.com'>跳转</a>")
        # 显示在xadmin列表中的名称
    go_to.short_description = "跳转"

    def get_course_lesson(self):
        """获取课程章节"""
        return self.lesson_set.all()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]


class BannerCourse(Course):
    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="所属课程")
    name = models.CharField(max_length=100, verbose_name="章节名")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = "章节"
        verbose_name_plural = verbose_name

    def get_lesson_video(self):
        return self.video_set.all()

    def __unicode__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name="所属章节")
    name = models.CharField(max_length=100, verbose_name="视频名")
    url = models.CharField(max_length=200, null=True, blank=True, verbose_name="视频地址")
    video_times = models.IntegerField(verbose_name="视频时长", default=0)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = "视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name="所属课程")
    name = models.CharField(max_length=100, verbose_name="资源名")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name="课程资源")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    class Meta:
        verbose_name = "资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

templates/index.html
{% extends 'base.html' %}
{% block title %}课程机构列表-暮雪在线{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
{% endblock %}
{% block custom_js %}
    <script src="{% static 'js/index.js' %}"  type="text/javascript"></script>
{% endblock %}

{% block content %}
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for banner in all_banners %}
                        <li>
                            <a href="">
                                <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>
    </div>
</div>
<section>
    <div class="wp">
        <ul class="feature">
            <li class="feature1">
                <img class="pic" src="{% static 'images/feature1.png' %}"/>
                <p class="center">专业权威</p>
            </li>
            <li class="feature2">
                <img class="pic" src="{% static 'images/feature2.png' %}"/>
                <p class="center">课程最新</p>
            </li>
            <li class="feature3">
                <img class="pic" src="{% static 'images/feature3.png' %}"/>
                <p class="center">名师授课</p>
            </li>
            <li class="feature4">
                <img class="pic" src="{% static 'images/feature4.png' %}"/>
                <p class="center">数据真实</p>
            </li>
        </ul>
    </div>
</section>
<section>
    <div class="module">
        <div class="wp">
            <h1>公开课程</h1>
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="{% static 'images/module1_1.jpg' %}"/>
                    <p class="fisrt_word">名师授课<br/>专业权威</p>
                    <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>
                </div>
                <div class="right group_list">
                    <div class="module1_2 box">
                        <div class="imgslide2">
                            <ul class="imgs">
                                {% for banner_course in banner_courses %}
                                <li>
                                    <a href="{% url 'course:course_detail' banner_course.id %}">
                                        <img width="470" height="300" src="{{ MEDIA_URL }}{{ banner_course.image }}" />
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="unslider-arrow2 prev"></div>
                        <div class="unslider-arrow2 next"></div>
                    </div>
                        {% for course in courses %}
                        <div class="module1_{{ forloop.counter|add:2 }} box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <h2 title="{{ course.name }}">{{ course.name }}</h2>
                                </a>
                                <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl" title="慕课网">{{ course.course_org.name }}</span>
                                <span class="star fr">{{ course.fav_nums }}</span>
                            </div>
                        </div>
                        {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="module greybg">
        <div class="wp">
            <h1>课程机构</h1>
            <div class="module3 eachmod">
                <div class="module3_1 left">
                    <img width="228" height="463" src="{% static 'images/module3_1.jpg' %}"/>
                    <p class="fisrt_word">名校来袭<br/>权威认证</p>
                    <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>
                </div>
                <div class="right">
                    <ul>
                        {% for course_org in course_orgs %}
                        <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">
                                <a href="{% url 'org:org_home' course_org.id %}">
                                    <div class="company">
                                        <img width="184" height="100" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                                        <div class="score">
                                            <div class="circle">
                                                <h2>{{ course_org.tag }}</h2>
                                            </div>
                                        </div>
                                    </div>
                                    <p><span class="key" title="慕课网">{{ course_org.name }}</span></p>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/org-list.html
{% extends 'base.html' %}
{% block title %}课程机构列表-暮雪在线{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>授课机构</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
        <div class="wp butler_list_box list">
        <div class='left'>
            <div class="listoptions">
                <ul>
                    <li>
                        <h2>机构类别</h2>
                        <div class="cont">
                            <a href="?city={{ city_id }}"><span {% ifequal category '' %} class="active2" {% endifequal %}>全部</span></a>

                                <a href="?ct=pxjg&city={{ city_id }}"><span {% ifequal category 'pxjg' %} class="active2" {% endifequal %}>培训机构</span></a>

                                <a href="?ct=gx&city={{ city_id }}"><span {% ifequal category 'gx' %} class="active2" {% endifequal %}>高校</span></a>

                                <a href="?ct=gr&city={{ city_id }}"><span {% ifequal category 'gr' %} class="active2" {% endifequal %}>个人</span></a>

                        </div>
                    </li>
                    <li>
                        <h2>所在地区</h2>
                        <div class="more">更多</div>
                        <div class="cont">
                            <a href="?ct={{ category }}"><span {% ifequal city_id '' %} class="active2" {% endifequal %}>全部</span></a>
                                {% for city in all_cities %}
                                    <a href="?ct={{ category }}&city={{ city.id }}"><span {% ifequal city_id city.id|stringformat:'i' %} class="active2" {% endifequal %}>{{ city.name }}</span></a>
                                {% endfor %}
                        </div>
                    </li>
                </ul>
            </div>
            <div class="all">共<span class="key">{{ page_datas.object_list.count }}</span>家</div>
            <div class="butler_list company list">
            <div class="layout">
                <div class="head">
                    <ul class="tab_header">
                        <li class="{% if sort == '' %}active{% endif %}"><a href="?ct={{ category }}&city={{ city_id }}">全部</a> </li>
                        <li class="{% if sort == 'students' %}active{% endif %}"><a href="?sort=students&ct={{ category }}&city={{ city_id }}">学习人数 &#8595;</a></li>
                        <li class="{% if sort == 'course_nums' %}active{% endif %}"><a href="?sort=course_nums&ct={{ category }}&city={{ city_id }}">课程数 &#8595;</a></li>
                    </ul>
                </div>
                {% for org in page_datas.object_list %}
                    <dl class="des difdes">
                        <dt>
                            <a href="{% url 'org:org_home' org.id %}">
                                <img width="200" height="120" class="scrollLoading" data-url="{{ MEDIA_URL }}{{ org.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <div class="clearfix">
                                 <a href="{% url 'org:org_home' org.id %}">
                                     <h1>{{ org.name }}</h1>
                                     <div class="pic fl">

                                             <img src="{% static 'images/authentication.png' %}"/>

                                             <img src="{% static 'images/gold.png' %}"/>

                                     </div>
                                 </a>
                            </div>
                            <ul class="cont">
                                <li class="first"><p class="pic9">课程数：<span></span></p><p class="c7">学习人数：<span>{{ org.click_nums }}</span></p></li>
                                <li class="c8" style="padding-left:18px;">{{ org.address }}</li>
                                <li class="pic10" style="padding-left:18px;">经典课程：
                                    {% for course in org.course_set.all %}
                                        <a href="{% url 'course:course_detail' course.id %}">{{ course.name }}</a>
                                    {% endfor %}
                                </li>
                            </ul>
                        </dd>
                        <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                    </dl>
                {% endfor %}
            </div>
                {# The following renders the pagination html #}
                {% include "_pagination.html" %}
            </div>
        </div>
        <div class="right companyright">
            <div class="head">我要学习</div>
            <form class="rightform" id="jsStayForm">
                <div>
                    <img src="{% static 'images/rightform1.png' %}"/>
                    <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25" />
                </div>
                <div>
                    <img src="{% static 'images/rightform2.png' %}"/>
                    <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                </div>
                <div>
                    <img src="{% static 'images/rightform3.png' %}"/>
                    <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50" />
                </div>
                <p class="error company-tips" id="jsCompanyTips"></p>
                {% csrf_token %}
                <input class="btn" type="button" id="jsStayBtn" value="立即咨询 >" />
            </form>
        </div>

        <div class="right companyrank layout">
            <div class="head">授课机构排名</div>
            {% for hot_org in hot_orgs %}
                <dl class="des">
                    <dt class="num fl">{{ forloop.counter }}</dt>
                    <dd>
                        <a href="{% url 'org:org_home' hot_org.id %}"><h1>{{ hot_org.name }}</h1></a>
                        <p>{{ hot_org.address }}</p>
                    </dd>
                </dl>
            {% endfor %}
        </div>
        </div>
    </section>
{% endblock %}
{% block ajax %}
<script>
    $(function(){
        $(document).ready(function() {
            $('#jsStayBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "{% url 'org:add_ask' %}",
                    data: $('#jsStayForm').serialize(),
                    async: true,
                    success: function (data) {
                        console.log(data)
                        if (data.status == 'success') {
                            $('#jsStayForm')[0].reset()
                            $('#jsCompanyTips').text("")
                            alert("提交成功")
                        } else if (data.status == 'fail') {
                            $('#jsCompanyTips').text(data.msg)
                        }
                    },
                });
            });
        });
    })
</script>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页 - 慕学网{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header header2">
            {% include '_top.html' %}
            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin
                         "data-favid="22" data-fav-type="1">
                         {% if has_fav %}已收藏{% else %}收藏{% endif %}
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
			<li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
			<li>{% block page_path %}机构首页{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li {% ifequal current_page 'home' %}class="active2"{% endifequal %}><a href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li {% ifequal current_page 'course' %}class="active2"{% endifequal %}><a href="{% url 'org:org_course' course_org.id %}">机构课程</a></li>
                <li {% ifequal current_page 'desc' %}class="active2"{% endifequal %}><a href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li {% ifequal current_page 'teacher' %}class="active2"{% endifequal %}><a href="{% url 'org:org_teacher' course_org.id %}">机构讲师</a></li>
			</ul>
		</div>
    {% block right_form %}
    {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>

<script type="text/javascript">

function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'org:add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$(document).ready(function() {
    $('.collectionbtn').on('click', function(){
        add_fav($(this), {{ course_org.id }}, 2);
    });
});
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $(document).ready(function() {
        $('.jsFavBtn').on('click', function () {
            var type = $(this).attr('data-fav-type');
            if (type == '1') {
                favPraise($(this), 'fav', 1, '收藏');

            } else if (type == '3') {
                favPraise($(this), 'fav', 3);

            } else if (type == '11') {
                favPraise($(this), 'pra', 1);

            } else if (type == '4') {
                favPraise($(this), 'fav', 4);

            }
        });
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>
{% block custom_js %}{% endblock %}
</body>
</html>